<input type="hidden" name="post_type[]" value="actualites" />
    <input type="hidden" name="post_type[]" value="publications" />
    <input type="hidden" name="post_type[]" value="projet-accompagnes" />
    <input type="hidden" name="post_type[]" value="notes-outils" />
    <input type="hidden" name="post_type[]" value="formation-evenement" />
    <input type="hidden" name="post_type[]" value="projet-partenaires" />
    <input type="hidden" name="post_type[]" value="domaines-expertises" />
    <input type="hidden" name="post_type[]" value="team-members" />
    <input type="hidden" name="post_type[]" value="nos-membres" />
    <input type="hidden" name="post_type[]" value="nos-mandats" />
    <input type="hidden" name="post_type[]" value="nieuwsfeed" />
    <input type="hidden" name="post_type[]" value="kenniscentrum" />
    <input type="hidden" name="post_type[]" value="praktijkverhaal" />
    <input type="hidden" name="post_type[]" value="workshops-en-events" />
    <input type="hidden" name="post_type[]" value="veelgestelde-vragen" />